---
title: "git_01"
author: "Michelle Benavides"
date: "July 16, 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
All in the golden afternoon  
Full leisurely we glide;  
For both our oars, with little skill,  
By little arms are plied,  
While little hands make vain pretense  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright —  
And this was odd, because it was  
The middle of the night.  

The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done —  
“It’s very rude of him,” she said,  
“To come and spoil the fun.”  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
From fairest creatures we desire increase,  
That thereby beauty’s rose might never die,  
But as the riper should by time decease,  
His tender heir might bear his memory:  
But thou contracted to thine own bright eyes,  
Feed’st thy light’s flame with self-substantial fuel,  
Making a famine where abundance lies,  
Thy self thy foe, to thy sweet self too cruel:  
Thou that art now the world’s fresh ornament, 
And only herald to the gaudy spring,  
Within thine own bud buriest thy content,  

And, tender churl, mak’st waste in niggarding: 
Pity the world, or else this glutton be,  
To eat the world’s due, by the grave and thee.  